language: node_js
node_js:
  - 12

install:
  - SKIP_SETUP=true yarn install

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn run lint:styles
  - yarn run lint:js
  - yarn run build:dist

dist: trusty
sudo: false
